[package]
name = "rawrendering"
version = "0.1.0"
edition = "2024"

[dependencies]
softbuffer = "0.4.8"
winit = "0.30.12"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[[bench]]
name = "render_bench"
harness = false